### ISSUE TITLE
Get rid of vendor lockin

### ISSUE THREAD

**Issue by KOLANICH** [sergeyvoronin/LowRankMatrixDecompositionCodes#1]

**Comment by BradKML** [comment]
I wanted to ask this, but has someone made a Python wrapper for this?

**Comment by KOLANICH** [comment]
There is no python wrapper for it, and it can be that you doesn't need it. For NNMF and PCA scikit-learn has own online implementations and that has solved my subproblem (though it turned out that the PCA was useless for the big problem).
